AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Metrics/LineLength:
  Max: 100

Style/MutableConstant:
  Enabled: false

# Dumb, but also brand new.
Style/NumericPredicate:
  Enabled: false

# Allows for raising Redd::ResponseErrors with a Response object.
Style/RaiseArgs:
  Enabled: false

# Many reddit calls demand a lot of parameters.
Metrics/ParameterLists:
  CountKeywordArgs: false

# Stop rubocop from complaining about large `describe` blocks.
Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Naming/FileName:
  Enabled: false
