sudo: false
language: ruby

rvm:
  - 2.1.10
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - jruby-9.1.9.0
  - ruby-head
  - jruby-head

matrix:
  allow_failures:
  - rvm: ruby-head
  - rvm: jruby-head

cache: bundler

before_install:
  - gem update --system
  - gem update --no-document
  - gem cleanup
